# Generated by Django 3.2 on 2023-10-30 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Slug doesn't correct", regex='^[-a-zA-Z0-9_]+$')], verbose_name='category_slug'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='genres_slug'),
        ),
    ]
