# Generated by Django 3.2 on 2023-10-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Genresgenres', to='reviews.genres', verbose_name='genreTitle_genres')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Titlestitles', to='reviews.title', verbose_name='genreTitle_titles')),
            ],
        ),
    ]
