# Generated by Django 3.2 on 2023-11-03 17:11

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Genres",
            new_name="Genre",
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.IntegerField(
                validators=[reviews.validators.validate_year],
                verbose_name="title_year",
            ),
        ),
    ]
