# Generated by Django 3.2 on 2023-10-29 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_genres_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', message='Slug doesnt correct')], verbose_name='category_slug'),
        ),
    ]
