# Generated by Django 3.2 on 2023-11-03 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_auto_20231103_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Slug doesn't correct",
                        regex="^[-a-zA-Z0-9_]+$",
                    )
                ],
                verbose_name="category_slug",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^[-a-zA-Z0-9_]+$"
                    )
                ],
                verbose_name="genres_slug",
            ),
        ),
    ]
